### ISSUE TITLE
Simplify environment setup

### ISSUE THREAD

**Issue by anitagraser** [vsbrumb/CAMA2022#3]
This could potentially simplify our notebook environment setups: https://github.com/giswqs/geospatial/blob/master/docs/index.ipynb

**Comment by vsbrumb** [comment]
I could add as a resource to the workshop page and also test the notebooks later this week with our setup! It is a great idea I think

**Comment by anitagraser** [comment]
I've had a look at the geospatial package. Unfortunalty, it doesn't work out of the box:

```
(geospatial) C:\Users\anita>python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:34:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import movingpandas as mpd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\movingpandas\__init__.py", line 6, in <module>
    from .trajectory import Trajectory  # noqa F401
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\movingpandas\trajectory.py", line 25, in <module>
    from .trajectory_plotter import _TrajectoryPlotter
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\movingpandas\trajectory_plotter.py", line 4, in <module>
    import hvplot.pandas  # noqa F401, seems necessary for the following import to work
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\hvplot\__init__.py", line 8, in <module>
    import holoviews as _hv
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\holoviews\__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\holoviews\annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\__init__.py", line 1, in <module>
    from . import layout # noqa
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\layout\__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\layout\accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\layout\base.py", line 11, in <module>
    from ..io.model import hold
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\io\__init__.py", line 9, in <module>
    from ..config import config
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\config.py", line 21, in <module>
    from .io.notebook import load_notebook
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\io\notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\panel\io\resources.py", line 24, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (E:\Anaconda\envs\mamba\envs\geospatial\lib\site-packages\jinja2\__init__.py)
```

So I had to manually downgrade jinja2 using:

`mamba install -c conda-forge jinja2=3.0`

![image](https://user-images.githubusercontent.com/590385/162627480-a7dca2f6-ad33-4a73-bf0c-2f2b4e67d91f.png)
